
networks:
  main1-net:
  main1-net:

volumes:
  main1-vol:
  main2-vol:
  
services:
  main:
    image: danielmuhr/gsd:main1
    build:
      context: .
      dockerfile: /main1/Dockerfile
    deploy:
      replicas: 10
    volumes:
      - type: volume
        source: main1-vol
        target: /app
  main2:
    image: danielmuhr/gsd:main2
    build:
      context: .
      dockerfile: /main2/Dockerfile2
    deploy:
      replicas: 5
    volumes:
      - type: volume
        source: main2-vol
        target: /app