services:
  main:
    image: danielmuhr/gsd:main1
    build:
      context: .
      dockerfile: /main1/Dockerfile
  main2:
    image: danielmuhr/gsd:main2
    build:
      context: .
      dockerfile: /main2/Dockerfile2